#!/bin/sh

# Constants

wd=$(pwd)
os=$(uname -s)

echo "Working Directory: $wd"
echo "Operating System: $os"

case $os in
	'Linux')
	dosbox=`which dosbox`
	;;
	'Darwin')
	# Use the proper application instead of requiring it in PATH
	dosbox=/Applications/DOSBox.app/Contents/MacOS/DOSBox
	;;
	'WindowsNT')
	echo 'Not yet implemented! Please file this as a bug.'
	exit 2
	;;
	*)
	echo "Unknown OS: '$os' If problems arise, please file a bug."
	dosbox=`which dosbox`
esac

echo "DOSBox Location: $dosbox"

conf_file=$wd/amc325.conf
real_conf_file=$wd/.amc325.conf-generated

# Basic error checking

if [ ! -f "$dosbox" ] ; then
  echo "Error: $dosbox does not exist"
  exit 3
fi

if [ ! -f "$conf_file" ] ; then
  echo "Error: $conf_file does not exist"
  exit 1
fi

# Figure out what the serial config line must be

# This may need to be /dev/cu.* instead of /dev/tty.*
serial_device=$(ls /dev/tty.* | awk '!/\/dev\/tty\.Bluetooth-Incoming-Port/')

num_serial=$(echo $serial_device | wc -l | xargs)

if [ -z "$serial_device" ]; then
	echo 'No serial devices found!'
	exit 4
fi

if [ "$num_serial" -gt 1 ]; then
	echo "Found the following serial devices:"
	echo $serial_device
	serial_device=$(echo $serial_device | head -n 1)
fi

echo "Using serial device: $serial_device"

serial_conf="serial1=directserial realport:${serial_device#/dev/}"

# Write our real config file

echo "# This file has been autogenerated from '$conf_file'." > "$real_conf_file"
echo '# Any changes you make will be overridden!' >> "$real_conf_file"
echo '' >> "$real_conf_file"

sed -e "s/^serial1=!serial!.*\$/${serial_conf}/" "$conf_file" >> "$real_conf_file"

echo "Wrote generated config to $real_conf_file"

# Finally launch DOSBox

echo 'Launching DOSBox'
echo '--------------------------'

"$dosbox" -conf "$real_conf_file"





